name: Rust CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly

    steps:
      - uses: actions/checkout@v4
      - name: Install Rust ${{ matrix.rust }}
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}

      - name: Check with pathfinder_geometry features
        run: cargo check --features pathfinder_geometry
      - name: Check without default features
        run: cargo check --no-default-features
      - name: Run tests
        run: cargo test
      - name: Run benchmarks with pathfinder_geometry features
        run: cargo bench --no-run --features pathfinder_geometry
      - name: Run benchmarks without default features
        run: cargo bench --no-default-features --no-run

      - name: Run after-success.sh
        run: |
          chmod +x after-success.sh
          ./after-success.sh
